site_name: CProblems
site_url: https://shivanshu-semwal.github.io/CProblems/
site_author: Shivanshu Semwal (semwalshivanshu@gmail.com)
site_description: Complete article on famous competitive programming problems.
copyright: > 
  <img alt="CC BY-NC" src="license.png">

docs_dir: articles
repo_url: https://github.com/shivanshu-semwal/CProblems
edit_uri: edit/master/articles/

theme:
  name: material
  custom_dir: overrides
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: material/cat
  favicon: material/cat

  features:
    - navigation.tracking # the URL changes with the active anchor
    - navigation.tabs # first top-level folders are shown as tabs
    - navigation.indexes # link an index page to its parent folder
    - navigation.top # show the back-to-top button
    - search.suggest # display the likeliest completion for the last word
    - search.highlight # highlight all occurrences
    - search.share # show a share button of the current search
    - content.code.annotate # add comment to code blocks

#
# Plugins
#
plugins:
  - search # must be included at the first place
  - git-revision-date-localized:
        enable_creation_date: true
        fallback_to_build_date: true
        type: iso_date
  - macros

#
# Extensions
#
markdown_extensions:
  - abbr # add a small tooltip to elements
  - admonition # add call-out blocks
  - attr_list # allow to add HTML attributes and CSS classes
  - def_list # add description lists
  - footnotes # define inline footnotes
  - meta # attach arbitrary key-value pairs to a document
  - md_in_html # allow to write Markdown inside HTML elements
  - tables # create tables in Markdown
  - toc: # generate a table of contents from documents
      permalink: '#' # anchor
      toc_depth: 4 # header 1 to header 4
      slugify: !!python/name:pymdownx.slugs.uslugify # convert title to html-compatible text
  - sane_lists # make better lists
  - smarty: # convert some special characters
      smart_angled_quotes: true
  #
  # Python Markdown Extensions
  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/
  #
  - pymdownx.arithmatex: # render math equations
      generic: true
  # - pymdownx.betterem: # improve the detection of Markup to emphasize text in Markdown
      # smart_enable: all
  - pymdownx.caret # define superscript
  - pymdownx.mark # highlight text
  - pymdownx.tilde # define subscript
  - pymdownx.critic # track changes
  - pymdownx.details # add collapsible call-outs
  - pymdownx.emoji: # add inlines bundled and custom icons and emojis 
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences # define code blocks and nesting of code
  - pymdownx.highlight: # highlight of code blocks
      linenums_style: pymdownx-inline
      # anchor_linenums: true # create anchor link on each line of code
  - pymdownx.inlinehilite # highlight inline code blocks
  - pymdownx.smartsymbols # convert some sequences of characters into their corresponding symbols
  - pymdownx.snippets #  embed content from arbitrary files into a document
  - pymdownx.tabbed: # group related content and code blocks under accessible tabs
      alternate_style: true
  - pymdownx.tasklist: # define list of task with checkbox
      custom_checkbox: true
  - pymdownx.escapeall:
      hardbreak: true # use \ to create new line
      nbsp: true # use \<space> to create &nbsp;
  # - pymdownx.keys # syntax ++ctrl+c++ does not look clear in MD document
  - pymdownx.progressbar

#
# Extras
#
extra:
  # https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-footer
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/shivanshu-semwal
      name: shivanshu-semwal
    - icon: fontawesome/brands/linkedin-in
      link: https://www.linkedin.com/in/shivanshu-semwal
      name: shivanshu-semwal
  generator: false # hide the line "Made with Material for MkDocs"

#
# Custom styles and scripts
#
extra_css:
  - assets/extra.css
extra_javascript:
  - assets/mathjax.js # must be before mathjax
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
